# Generated by Django 4.2.7 on 2023-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Status:'),
        ),
    ]
