# Generated by Django 4.2.7 on 2023-12-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
